name: Build

on: [push]
jobs:
  build:
    name: "Build source code"
    runs-on: ubuntu-22.04
    env:
        CC: clang-16
        CXX: clang++-16
        CLANG_DIR: '/usr/lib/llvm-16/lib/cmake/clang'
        LLVM_DIR: '/usr/lib/llvm-16/lib/cmake/llvm'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install a compiler toolchain
        run: |
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
            sudo apt update
            sudo apt install llvm-16 llvm-16-dev llvm-16-tools clang-16 clang-tidy-16 clang-tools-16 libclang-16-dev lld-16
      - name: Build weekly code
        run: |
          mkdir -p out
          for file in ./week_*/*/*.cpp; do
            clang++ -std=c++20 -Wall -Wextra -Wpedantic -Wconversion "$file" -o ./out/$(basename "$file" .cpp).o
          done
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out 
          path: |
            out
